version: '3.9'
services:
  power-dns:
    build:
      context: .
      dockerfile: Dockerfile
    ports: []
      # - "5335:5335/udp"
      # - "5335:5335/tcp"
      # - "8000:8000"
    environment:
      - PUBLIC_DOH_SERVER=https://your-public-doh-server

    labels:
      - "traefik.http.services.power-dns.loadbalancer.server.port=8000"
      - "traefik.http.routers.power-dns.rule=PathPrefix(`/pdns`)"
      - "traefik.http.middlewares.pwer-dns.stripprefix.prefixes=/pdns"
      - "traefik.http.routers.power-dns.middlewares=pwer-dns@docker"

    networks:
      - prod-automation_prod-auto-inet

networks:
  prod-automation_prod-auto-inet:
    external: true